Add accordion component
IBM/carbon-components-builder pull request #57
Opened 2022-02-17 22:58 UTC by Donisius

Closes #38

2022-02-23 20:44 UTC, zvonimirfras requested changes
It would be cool if the Adder supported all directions, configurable.

2022-02-23 20:44 UTC, zvonimirfras commented on src/fragment-components/accordion/a-accordion-item.tsx
> +			inputs: ({json}) => ``,
no inputs an outputs? 🤔

2022-02-23 20:44 UTC, zvonimirfras commented on src/fragment-components/accordion/a-accordion.tsx
> +			{
Do we need 3 items?

2022-03-16 18:03 UTC, Akshat55 commented on src/fragment-components/accordion/a-accordion-item.tsx
> +import { Adder, getParentComponent, updatedState } from '../../components';
```suggestion
import { 
    Adder, 
    getParentComponent, 
    updatedState 
} from '../../components';
```

2022-03-16 18:20 UTC, Akshat55 requested changes

2022-03-16 18:20 UTC, Akshat55 commented on src/fragment-components/accordion/a-accordion-item.tsx
> +import { Adder, getParentComponent, updatedState } from '../../components';
```suggestion
import { 
    Adder, 
    getParentComponent, 
    updatedState 
} from '../../components';
```

2022-03-16 18:20 UTC, Akshat55 commented on src/fragment-components/accordion/a-accordion-item.tsx
> +			))}
```suggestion
			{componentObj.items.map((child: any) => renderComponents(child))}
```

2022-03-16 18:20 UTC, Akshat55 commented on src/fragment-components/accordion/a-accordion.tsx
> +		))}
Same as above - saves space 😛

2022-03-18 19:02 UTC, zvonimirfras approved these changes

2022-03-18 19:10 UTC, Akshat55 reviewed
Can approve right after that small lint fix

2022-03-23 20:27 UTC, Akshat55 requested changes
<img width="619" alt="image" src="https://user-images.githubusercontent.com/38994122/159788834-6ba49009-a2b8-459a-b4f0-59b531141abd.png">
When you click on the text in accordion item, the component classifier box appears as if it is transparent. Need to update `z-index` to fix this.

2022-03-24 20:17 UTC, Akshat55 approved these changes

2022-03-24 20:32 UTC, merged