updated
IBM/carbon-components-builder pull request #72
Opened 2022-04-19 22:24 UTC by MoizMasud

I think we merged in the wrong order, tiles were missing the mapping. have added them below

2022-04-20 01:53 UTC, Akshat55 requested changes

2022-04-20 01:53 UTC, Akshat55 commented on src/fragment-components/tiles/a-clickable-tile.tsx
> +	type: 'clickabletile',
```suggestion
	type: 'clickable-tile',
```

2022-04-20 01:53 UTC, Akshat55 commented on src/fragment-components/tiles/a-clickable-tile.tsx
> +	type: 'clickabletile',
Thought we agreed to use a dashed naming convention for types? Should also apply to all of the ones below except `tile`

2022-04-20 01:53 UTC, Akshat55 commented on src/fragment-components/tiles/a-expandable-tile.tsx
> +	type: 'expandabletile',
```suggestion
	type: 'expandable-tile',
```

2022-04-20 01:53 UTC, Akshat55 commented on src/fragment-components/tiles/a-radio-tile-group.tsx
> +	type: 'radioTileGroup',
```suggestion
	type: 'radio-tile-group',
```

2022-04-20 01:53 UTC, Akshat55 commented on src/fragment-components/tiles/a-radio-tile.tsx
> +	type: 'radiotile',
```suggestion
	type: 'radio-tile',
```

2022-04-20 01:53 UTC, Akshat55 commented on src/fragment-components/tiles/a-selectable-tile-group.tsx
> +	type: 'selectabletile',
```suggestion
	type: 'selectable-tile-group',
```

2022-04-20 01:53 UTC, Akshat55 commented on src/fragment-components/tiles/a-selectable-tile-group.tsx
> +	type: 'selectabletile',
Should add group here since there is a component with `selectable-tile` as type

2022-04-20 01:53 UTC, Akshat55 commented on src/fragment-components/tiles/a-selectable-tile.tsx
> +	type: 'selectabletile',
```suggestion
	type: 'selectable-tile',
```

2022-04-20 01:53 UTC, Akshat55 commented on src/fragment-components/tiles/a-tile-fold.tsx
> +	type: 'tilefold',
```suggestion
	type: 'tile-fold',
```

2022-04-20 13:46 UTC, zvonimirfras approved these changes

2022-04-20 19:05 UTC, Akshat55 requested changes

2022-04-20 19:05 UTC, Akshat55 commented on src/fragment-components/tiles/a-radio-tile-group.tsx
>  		type: 'radioTileGroup',
Shouldn't this be radio-tile-group?

```suggestion
		type: 'radio-tile-group',
```

2022-04-20 19:05 UTC, Akshat55 commented on src/fragment-components/tiles/a-selectable-tile-group.tsx
>  		type: 'selectableTileGroup',
```suggestion
		type: 'selectable-tile-group',
```

2022-04-21 05:10 UTC, Akshat55 requested changes
You also update the component type in tile-morphism

2022-04-21 17:40 UTC, Akshat55 requested changes

2022-04-21 17:40 UTC, Akshat55 commented on src/fragment-components/tiles/tile-morphism.tsx
> +			type: 'tile',
This isn't needed, the type is defined in defaultComponent - this isn't being used anywhere. Can you try removing and try morhping the tiles? It should still work

2022-04-21 17:40 UTC, Akshat55 commented on src/fragment-components/tiles/tile-morphism.tsx
> +			type: 'clickable-tile',
Remove, same comment as above `Tile`

2022-04-21 17:40 UTC, Akshat55 commented on src/fragment-components/tiles/tile-morphism.tsx
> +			type: 'expandable-tile',
remove

2022-04-21 17:40 UTC, Akshat55 commented on src/fragment-components/tiles/tile-morphism.tsx
> +			type: 'selectable-tile',
Remove

2022-04-21 17:40 UTC, Akshat55 commented on src/fragment-components/tiles/tile-morphism.tsx
> +			type: 'selectable-tile-group',
Remove

2022-04-21 17:40 UTC, Akshat55 commented on src/fragment-components/tiles/tile-morphism.tsx
> +			type: 'radio-tile-group',
Remove

2022-04-21 18:53 UTC, Akshat55 approved these changes

2022-04-22 14:45 UTC, zvonimirfras approved these changes

2022-04-22 14:46 UTC, merged